# QUERY
QUERY: "Is there something wrong with my face?"

# Base URL
BASE_URL: "https://ds4sd.github.io/docling/"

# Document Path
PDF_PATH: "https://arxiv.org/pdf/2408.09869"
HTML_DOC_PATH: "https://ds4sd.github.io/docling/"

# LLM
LLM:
    PROVIDER: openai
    MODEL: "gpt-4o-mini"
    TEMPERATURE: 0.7
    MAX_TOKENS: 8191

# Embeddings
EMBEDDINGS:
    PROVIDER: openai
    MODEL: "text-embedding-3-large"

# Vector DB
VECTOR_DB: 
    URI: "vector_db/lancedb"
    TABLE_NAME: "docling"
    MODE: "overwrite"
    LIMIT: 5

COMMON_TLDS:
  - ".com"
  - ".org"
  - ".net"
  - ".edu"
  - ".gov"
  - ".io"
  - ".ai"
  - ".co"
  - ".uk"
  - ".ca"
  - ".jp"
  - ".de"
  - ".fr"
  - ".it"
  - ".es"
  - ".ru"
  - ".in"
  - ".au"
  - ".nz"
  - ".se"
  - ".nl"
  - ".be"
  - ".at"
  - ".ch"
  - ".dk"
  - ".no"
  - ".fi"
  - ".pl"
  - ".cz"
  - ".gr"
  - ".pt"
  - ".mx"
  - ".za"
  - ".kr"
  - ".sg"
  - ".tw"
  - ".hk"
  - ".jp"
  - ".cn"
  - ".au"
  - ".nz"
  - ".se"
  - ".nl"
  - ".be"
  - ".at"
  - ".ch"
  - ".dk"
  - ".no"
  - ".fi"
  - ".pl"
  - ".cz"
  - ".gr"
  - ".pt"
  - ".mx"
  - ".za"
  - ".kr"
  - ".sg"
  - ".tw"
  - ".hk"
  - ".jp"
  - ".cn"
  - ".au"
  - ".nz"
  - ".se"
  - ".nl"
  - ".be"
  - ".at"
  - ".ch"
  - ".dk"
  - ".no"
  - ".fi"
  - ".pl"
  - ".cz"
  - ".gr"
  - ".pt"
  - ".mx"
  - ".za"
  - ".kr"
  - ".sg"
  - ".tw"
  - ".hk"